export enum Status {
REQUESTED = 'REQUESTED',
ACCEPTED = 'ACCEPTED',
DECLINED = 'DECLINED',
DONE_WAITING_FOR_FEEDBACK = 'DONE_WAITING_FOR_FEEDBACK',
FINISHED_FEEDBACK_GIVEN = 'FINISHED_FEEDBACK_GIVEN',
FINISHED_AUTOMATICALLY_CLOSED = 'FINISHED_AUTOMATICALLY_CLOSED',
FINISHED_CANCELLED_BY_COACHEE = 'FINISHED_CANCELLED_BY_COACHEE',
FINISHED_CANCELLED_BY_COACH = 'FINISHED_CANCELLED_BY_COACH',
}
